linters-settings:
  funlen:
    lines: 75
linters:
  disable-all: true
  enable:
    - asciicheck
    - bodyclose
    - depguard
    - dogsled
    - dupl
    - errcheck
    - funlen
    - gocognit
    - goconst
    # - gocritic
    - gocyclo
    - gofmt
    - goimports
    - revive  # Replace golint with revive
    - goprintffuncname
    - gosec
    - gosimple
    - govet
    - ineffassign
    - misspell
    - nakedret
    - nolintlint
    - prealloc
    - staticcheck
    - stylecheck
    - unconvert
    - unparam
    - unused  # This will cover deprecated checks
    - whitespace

# do not enable...
#    - gochecknoglobals
#    - gochecknoinits    # this is too aggressive
#    - godot
#    - godox
#    - goerr113
#    - gomnd       # this is too aggressive
#    - interfacer  # this is a good idea, but is no longer supported and is prone to false positives
#    - lll         # without a way to specify per-line exception cases, this is not usable
#    - nestif
#    - testpackage
#    - wsl